name: Cypress Tests

on:   
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  schedule:
    - cron: "0 0 * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          yarn install

      - name: Run Cypress Test
        uses: cypress-io/github-action@v6
        with:
         command: yarn run cy:run

    - uses: actions/upload-artifact@v2
       if: failure()
       with:
         name: cypress-screenshots
         path: ./cypress/screenshots
     - uses: actions/upload-artifact@v2
       if: always()
       with:
         name: cypress-videos
         path: ./cypress/videos
